language: cpp

script:
  - git clone --recursive --depth 1 https://github.com/alberthdev/spasm-ng.git
  - cd spasm-ng
  - make NO_APPSIGN=1 -j2
  - cp ./spasm ../spasm
  - cd ..
  - ./spasm -E -A launcher.asm TIBOYCE.8xp
  - ./spasm -E -A tiboyce.asm TIBoyDat.8xv
  - ./spasm -E -A skin.asm TIBoySkn.8xv
  - cd tiboyce-romgen
  - gcc -std=c99 -O2 -W -Wall -Wextra -Wno-pointer-sign -Wno-unused-parameter -o romgen romgen.c zip.c
  - cd ../tiboyce-convertsav
  - gcc -std=c99 -O2 -W -Wall -Wextra -Wno-pointer-sign -Wno-unused-parameter -o convertsav convertsav.c lzf_c.c lzf_d.c

notifications:
  irc:
    channels:
      - "irc.choopa.net#ez80-dev"
    on_success: change
    on_failure: always
    skip_join: true
